name: Deploy Sistem Toko Dashboard

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Lint check
        run: |
          pip install flake8
          # Linting checking syntax error saja (E9,F63,F7,F82) agar tidak menghambat deployment
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: Login to GHCR
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: docker build -t ghcr.io/${{ github.actor }}muhammadrevaldy/sistemtoko-dashboard:latest dashboard/

      - name: Push image
        run: docker push ghcr.io/${{ github.actor }}muhammadrevaldy/sistemtoko-dashboard:latest

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker pull ghcr.io/${{ github.actor }}/sistemtoko-dashboard:latest
            docker stop sistemtoko-dashboard || true
            docker rm sistemtoko-dashboard || true
            docker run -d --name sistemtoko-dashboard \
              -p 8080:8080 \
              -e AWS_DEFAULT_REGION=ap-southeast-1 \
              --restart always \
              ghcr.io/${{ github.actor }}muhammadrevaldy/sistemtoko-dashboard:latest
